# Generated by Django 5.0 on 2024-01-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stdent",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID",),),
                ("name", models.CharField(max_length=200)),
                ("college", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("is_Active", models.BooleanField(default=False)),
            ],
        ),
    ]
